services:
  fiap.mctech.api:
    container_name: mctech_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      CONNECTION_STRING: Server=sqlserver,1433;Initial Catalog=mctech;User Id=sa;Password=${SA_PASSWORD};
      ALLOW_SWAGGER_UI: true

      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
      OPENID_AUDIENCE: ${OPENID_AUDIENCE}
    ports:
      - "8081:8081"
    networks:
      - local_network 
      - db_network

  sqlserver:
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db_network

  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  db_network:

volumes:
  sqlserver_data:
  keycloak_data:  