services:
  fiap.mctech.api:
    container_name: mctech_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      CONNECTION_STRING: Server=sqlserver,1433;Initial Catalog=mctech;User Id=sa;Password=pws4mctech!;
      ALLOW_SWAGGER_UI: true

      OPENID_AUTHORITY: http://keycloak:8080/realms/McTech
      OPENID_CLIENT_ID: mctech-api
      OPENID_CLIENT_SECRET: w7FPSkF3IcA8ibmQivri3nznqZIMMExf
    ports:
      - "8081:8081"
    networks:
      - local_network 
      - db_network

  sqlserver:
    container_name: sqlserver
    environment:
      SA_PASSWORD: pws4mctech!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    container_name: keycloak
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
     - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  db_network:

volumes:
  sqlserver_data:
  keycloak_data:  