version: '3.4'

services:
  fiap.mctech.api:
    depends_on:
      - sqlserver
    image: ${DOCKER_REGISTRY-}fiapmctechapi
    build:
      context: .
      dockerfile: src/Fiap.McTech.Api/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"