services:
  fiap.mctech.api:
    depends_on:
      - sqlserver
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/api
    build:
      context: .
      dockerfile: src/Fiap.McTech.Api/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    restart: always
    command: start-dev
    environment:
      KC_HOSTNAME: keycloak