apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit-range
  namespace: mctech-api-space
spec:
  limits:
  - default:
      ephemeral-storage: "2Gi"
    type: Container

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mctechapi
  namespace: mctech-api-space
  labels:
    app: mctechapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mctechapi
  template:
    metadata:
      labels:
        app: mctechapi
    spec:
      containers:
        - name: mctechapi-container
          image: ghcr.io/grupo-68-fiap/mctech/api:latest # NOSONAR
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mctechapi-secret
                  key: CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: mctechapi-configmap
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
            limits:
              memory: 256Mi
              cpu: 200m
      automountServiceAccountToken: false
