apiVersion: v1 # secret com dados sensíveis usados na API
kind: Secret
metadata:
  name: mctechapi-secret
type: Opaque
data:
  ASPNETCORE_Kestrel__Certificates__Default__Password: cHdzNG1jdGVjaCE=
  CONNECTION_STRING: U2VydmVyPW1jdGVjaC1zcWxzZXJ2ZXJkYi1yZHMtaW5zdGFuY2UuY2Q0ZmVhcjZ5aHhjLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbSwxNDMzO0luaXRpYWwgQ2F0YWxvZz1tY3RlY2g7VXNlciBJZD1tY3RlY2g7UGFzc3dvcmQ9Y2hhbmdlaXQxMjM7

---

apiVersion: v1 # ConfigMap com valores variáveis usados no deploymentConfig
kind: ConfigMap
metadata:
  name: mctechapi-configmap
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:80
  ALLOW_SWAGGER_UI: 'true'