apiVersion: v1
kind: PersistentVolume
metadata:
  name: mctech-pv-sqlserver
  labels:
    name: mctech-pv-sqlserver
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /c/mctech/sqlserver/data