apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mctech-pvc-sqlserver
  labels:
    name: mctech-pvc-sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: local-storage-db