apiVersion: v1 # Secret para dados sensíveis de acesso à BD
kind: Secret
metadata:
  name: mctech-secret-sqlserver
type: Opaque
data:
  SQLSERVER_DB: bWN0ZWNo
  MSSQL_SA_PASSWORD: cHdzNG1jdGVjaCE=
    
---

apiVersion: v1 # configMap com valores variáveis usados no deploymentConfig
kind: ConfigMap
metadata:
  name: mctech-configmap-sqlserver
data:
  ACCEPT_EULA: 'Y'
  MSSQL_PID: Developer