apiVersion: apps/v1
kind: Deployment
metadata:
  name: mctech-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mctech-sqlserver
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: mctech-sqlserver
    spec:
      containers:
      - name: mctech-sqlserver
        image: mcr.microsoft.com/mssql/server:latest
        env:
          - name: SQLSERVER_DB
            valueFrom:
              secretKeyRef:
                name: mctech-secret-sqlserver
                key: SQLSERVER_DB
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mctech-secret-sqlserver
                key: MSSQL_SA_PASSWORD
        envFrom:
          - configMapRef:
              name: mctech-configmap-sqlserver
        ports:
        - containerPort: 1433
          name: sqlserver
        resources:
          limits:
            memory: 3Gi
            cpu: 1000m
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
        volumeMounts:
          - mountPath: /var/opt/mssql
            name: mssql            
      volumes:
        - name: mssql
          persistentVolumeClaim:
            claimName: mctech-pvc-sqlserver
      securityContext:
        fsGroup: 10001 #configuração necessária por conta de erro de permissão ao criar pasta do volumeMount dentro do container
        runAsUser: 0