apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: mctech-sqlserver-svc
spec:
  selector:
    app: mctech-sqlserver
  ports:
    - name: tcp
      protocol: TCP
      port: 1433
      targetPort: 1433
  clusterIP: None