// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fiap.McTech.FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDePedidosFeature : object, Xunit.IClassFixture<GerenciamentoDePedidosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Orders.feature"
#line hidden
        
        public GerenciamentoDePedidosFeature(GerenciamentoDePedidosFeature.FixtureData fixtureData, Fiap_McTech_FunctionalTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Gerenciamento de Pedidos", "  Cen�rio: Criar um novo pedido com cliente autenticado\r\n    Dado que eu tenho um" +
                    " cliente autenticado\r\n    E que eu tenho os detalhes do pedido\r\n    Quando eu cr" +
                    "io um novo pedido\r\n    Ent�o o status da resposta deve ser 201 Created\r\n    E o " +
                    "pedido deve existir no sistema\r\n    E os dados do pedido devem corresponder ao f" +
                    "ormato esperado\r\n\r\n  Cen�rio: Criar um novo pedido sem cliente\r\n    Dado que eu " +
                    "tenho os detalhes do pedido sem cliente\r\n    Quando eu crio um novo pedido\r\n    " +
                    "Ent�o o status da resposta deve ser 400 BadRequest\r\n    E a mensagem de erro dev" +
                    "e ser \"Cliente n�o autenticado\"\r\n\r\n  Cen�rio: Adicionar item ao pedido existente" +
                    "\r\n    Dado que um pedido existe no sistema\r\n    E que eu tenho os detalhes do it" +
                    "em\r\n    Quando eu adiciono o item ao pedido\r\n    Ent�o o status da resposta deve" +
                    " ser 200 OK\r\n    E o item deve ser adicionado ao pedido\r\n    E os dados do pedid" +
                    "o devem ser atualizados no sistema\r\n\r\n  Cen�rio: Tentar criar um pedido com prod" +
                    "uto inexistente\r\n    Dado que eu tenho os detalhes do pedido com produto inexist" +
                    "ente\r\n    Quando eu crio um novo pedido\r\n    Ent�o o status da resposta deve ser" +
                    " 404 Not Found\r\n    E a mensagem de erro deve ser \"Produto n�o encontrado\"\r\n\r\n  " +
                    "Cen�rio: Tentar criar um pedido com cliente inexistente\r\n    Dado que eu tenho o" +
                    "s detalhes do pedido com cliente inexistente\r\n    Quando eu crio um novo pedido\r" +
                    "\n    Ent�o o status da resposta deve ser 404 Not Found\r\n    E a mensagem de erro" +
                    " deve ser \"Cliente n�o encontrado\"\r\n\r\n  Cen�rio: Atualizar um pedido existente\r\n" +
                    "    Dado que um pedido existe no sistema\r\n    E que eu tenho os novos detalhes d" +
                    "o pedido\r\n    Quando eu atualizo o pedido\r\n    Ent�o o status da resposta deve s" +
                    "er 200 OK\r\n    E os dados do pedido devem ser atualizados no sistema\r\n\r\n  Cen�ri" +
                    "o: Remover um pedido existente\r\n    Dado que um pedido existe no sistema\r\n    Qu" +
                    "ando eu removo o pedido\r\n    Ent�o o status da resposta deve ser 204 No Content\r" +
                    "\n    E o pedido n�o deve mais existir no sistema\r\n\r\n  Cen�rio: Tentar remover um" +
                    " pedido inexistente\r\n    Dado que eu tenho um ID de pedido inexistente\r\n    Quan" +
                    "do eu removo o pedido\r\n    Ent�o o status da resposta deve ser 404 Not Found\r\n  " +
                    "  E a mensagem de erro deve ser \"Pedido n�o encontrado\"", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDePedidosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDePedidosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
