// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fiap.McTech.FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDePagamentosFeature : object, Xunit.IClassFixture<GerenciamentoDePagamentosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Payments.feature"
#line hidden
        
        public GerenciamentoDePagamentosFeature(GerenciamentoDePagamentosFeature.FixtureData fixtureData, Fiap_McTech_FunctionalTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Gerenciamento de Pagamentos", "  Para garantir que os pagamentos sejam processados corretamente\r\n  Como um siste" +
                    "ma de pagamento\r\n  Eu quero ser capaz de criar, atualizar e remover pagamentos\r\n" +
                    "\r\n  Cen�rio: Criar um novo pagamento\r\n    Dado que eu tenho os detalhes do pagam" +
                    "ento\r\n    Quando eu crio um novo pagamento\r\n    Ent�o o status da resposta deve " +
                    "ser 201 Created\r\n    E o pagamento deve existir no sistema\r\n    E os dados do pa" +
                    "gamento devem corresponder ao formato esperado\r\n\r\n  Cen�rio: Criar um pagamento " +
                    "com dados inv�lidos\r\n    Dado que eu tenho os detalhes do pagamento com dados in" +
                    "v�lidos\r\n    Quando eu crio um novo pagamento\r\n    Ent�o o status da resposta de" +
                    "ve ser 400 BadRequest\r\n    E a mensagem de erro deve ser \"Dados do pagamento inv" +
                    "�lidos\"\r\n\r\n  Cen�rio: Atualizar um pagamento existente\r\n    Dado que um pagament" +
                    "o existe no sistema\r\n    E que eu tenho os novos detalhes do pagamento\r\n    Quan" +
                    "do eu atualizo o pagamento\r\n    Ent�o o status da resposta deve ser 200 OK\r\n    " +
                    "E os dados do pagamento devem ser atualizados no sistema\r\n\r\n  Cen�rio: Atualizar" +
                    " um pagamento com dados inv�lidos\r\n    Dado que um pagamento existe no sistema\r\n" +
                    "    E que eu tenho os novos detalhes do pagamento com dados inv�lidos\r\n    Quand" +
                    "o eu atualizo o pagamento\r\n    Ent�o o status da resposta deve ser 400 BadReques" +
                    "t\r\n    E a mensagem de erro deve ser \"Dados do pagamento inv�lidos\"\r\n\r\n  Cen�rio" +
                    ": Remover um pagamento existente\r\n    Dado que um pagamento existe no sistema\r\n " +
                    "   Quando eu removo o pagamento\r\n    Ent�o o status da resposta deve ser 204 No " +
                    "Content\r\n    E o pagamento n�o deve mais existir no sistema\r\n\r\n  Cen�rio: Tentar" +
                    " remover um pagamento inexistente\r\n    Dado que eu tenho um ID de pagamento inex" +
                    "istente\r\n    Quando eu removo o pagamento\r\n    Ent�o o status da resposta deve s" +
                    "er 404 Not Found\r\n    E a mensagem de erro deve ser \"Pagamento n�o encontrado\"", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDePagamentosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDePagamentosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
