// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fiap.McTech.FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeProdutosFeature : object, Xunit.IClassFixture<GerenciamentoDeProdutosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Products.feature"
#line hidden
        
        public GerenciamentoDeProdutosFeature(GerenciamentoDeProdutosFeature.FixtureData fixtureData, Fiap_McTech_FunctionalTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Gerenciamento de Produtos", @"  Cen�rio: Criar um novo produto
    Dado que eu inseri ""Product 1"" como o nome do produto
    E que eu inseri 10 como o valor do produto
    E que eu inseri ""Product description"" como a descri��o do produto
    E que eu inseri ""img"" como a imagem do produto
    E que eu selecionei ""Snack"" como a categoria do produto
    Quando eu crio o produto
    Ent�o o produto deve ser criado com sucesso

  Cen�rio: Criar um produto com valor negativo
    Dado que eu inseri ""Product 2"" como o nome do produto
    E que eu inseri -5 como o valor do produto
    E que eu inseri ""Product description"" como a descri��o do produto
    E que eu inseri ""img"" como a imagem do produto
    E que eu selecionei ""Snack"" como a categoria do produto
    Quando eu crio o produto
    Ent�o a cria��o do produto deve falhar com ""Invalid product value""

  Cen�rio: Remover um produto existente
    Dado que um produto existe no sistema
    Quando eu removo o produto
    Ent�o o produto n�o deve mais existir no sistema
    E o status da resposta deve ser 204 No Content

  Cen�rio: Atualizar um produto existente
    Dado que um produto existe no sistema
    Quando eu atualizo o produto com novos dados
    Ent�o o produto deve ser atualizado com sucesso
    E o status da resposta deve ser 200 OK", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeProdutosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeProdutosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
