apiVersion: v1 # Persistence Volume do sqlserver
kind: PersistentVolume
metadata:
  name: mctech-pv-sqlserver
  labels:
    name: mctech-pv-sqlserver
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /c/mctech/sqlserver/data

---

apiVersion: v1 # PersistentVolumeClaim do sql server
kind: PersistentVolumeClaim
metadata:
  name: mctech-pvc-sqlserver
  labels:
    name: mctech-pvc-sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: manual

---

apiVersion: v1 # Secret para dados sensíveis de acesso à BD
kind: Secret
metadata:
  name: mctech-secret-sqlserver
type: Opaque
data:
  SQLSERVER_DB: bWN0ZWNo
  MSSQL_SA_PASSWORD: cHdzNG1jdGVjaCE=
    
---

apiVersion: v1 # ConfigMap com valores variáveis usados no deploymentConfig
kind: ConfigMap
metadata:
  name: mctech-configmap-sqlserver
data:
  ACCEPT_EULA: 'Y'
  MSSQL_PID: Developer

---

apiVersion: apps/v1 # DeploymentConfig do sqlserver
kind: Deployment
metadata:
  name: mctech-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mctech-sqlserver
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: mctech-sqlserver
    spec:
      containers:
      - name: mctech-sqlserver
        image: mcr.microsoft.com/mssql/server:latest
        env:
          - name: SQLSERVER_DB
            valueFrom:
              secretKeyRef:
                name: mctech-secret-sqlserver
                key: SQLSERVER_DB
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mctech-secret-sqlserver
                key: MSSQL_SA_PASSWORD
        envFrom:
          - configMapRef:
              name: mctech-configmap-sqlserver
        ports:
        - containerPort: 1433
          name: sqlserver
        resources:
          limits:
            memory: 3Gi
            cpu: 1000m
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
        volumeMounts:
          - mountPath: /var/opt/mssql
            name: mssql            
      volumes:
        - name: mssql
          persistentVolumeClaim:
            claimName: mctech-pvc-sqlserver
      securityContext:
        fsGroup: 10001 # configuração necessária por conta de erro de permissão ao criar pasta do volumeMount dentro do container
        runAsUser: 0

--- 

apiVersion: v1 # Service para comunicação da API à BD
kind: Service
metadata:
  labels:
    app: sqlserver
  name: mctech-sqlserver-svc
spec:
  selector:
    app: mctech-sqlserver
  ports:
    - name: tcp
      protocol: TCP
      port: 1433
      targetPort: 1433
  clusterIP: None