apiVersion: v1 # secret com dados sensíveis usados na API
kind: Secret
metadata:
  name: mctechapi-secret
type: Opaque
data:
  ASPNETCORE_Kestrel__Certificates__Default__Password: cHdzNG1jdGVjaCE=
  CONNECTION_STRING: U2VydmVyPW1jdGVjaC1zcWxzZXJ2ZXItc3ZjLDE0MzM7SW5pdGlhbCBDYXRhbG9nPW1jdGVjaDtVc2VyIElkPXNhO1Bhc3N3b3JkPXB3czRtY3RlY2ghOw==
  
---

apiVersion: v1 # configMap com valores variáveis usados no deploymentConfig
kind: ConfigMap
metadata:
  name: mctechapi-configmap
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: https://+:443;http://+:80
  ALLOW_SWAGGER_UI: 'true'
