apiVersion: apps/v1
kind: Deployment
metadata:
  name: mctechapi
  labels:
    app: mctechapi
spec:
  template:
    metadata:
      name: mctechapi
      labels:
        app: mctechapi
    spec:
      containers:
        - name: mctechapi-container
          image: ghcr.io/grupo-68-fiap/mctech/api:dev
          env:
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              valueFrom:
                secretKeyRef:
                  name: mctechapi-secret
                  key: ASPNETCORE_Kestrel__Certificates__Default__Password
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /app/cert.pfx
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mctechapi-secret
                  key: CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: mctechapi-configmap
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          livenessProbe:
            httpGet:
              path: /swagger # adicionar URL de health
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger # adicionar URL de health
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
            limits:
              memory: 1024Mi
              cpu: 500m
  replicas: 1
  selector:
    matchLabels:
      app: mctechapi
