name: AWS Deploying

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "Container Publish" ]
    types: [ completed ]
    branches: [ master, develop ]

env:
  REGION_DEFAULT: us-east-1
  EKS_CLUSTER_NAME: MechTechApi

jobs:

  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: container-publish
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.REGION_DEFAULT }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy to AWS
        run: |
          kubectl apply -f k8s/
