name: .NET

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "*" ]
    paths-ignore: [ "**/*.md" ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Fiap.McTech.Api/Fiap.McTech.Api.csproj

    - name: Build
      run: dotnet build src/Fiap.McTech.Api/Fiap.McTech.Api.csproj --configuration Release

    - name: Test
      run: dotnet test src/Fiap.McTech.Api/Fiap.McTech.Api.csproj --verbosity normal

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v4
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "latest"
        else
          echo "${{ github.ref/refs/heads/ }}"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./src/Fiap.McTech.Api
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fiap-mctech-api:${{ steps.docker_tag.outputs.tag }}
